title: Series of Hackintosh
subtitle: Author - Minh Mon
description: >- # this means to ignore newlines until "baseurl:"
  Tutorial about Hackintosh, Setup and so on
baseurl: "" # the subpath of your site, e.g. /blog
url: "minmon98.github.io" # the base hostname & protocol for your site, e.g. http://example.com

author_logo: profile.png
disqus_shortname: sujay-kundu  #for comments using disqus
author: devlopr
author_bio: Hello, my name is John Doe.I am an award winning Full Stack Web Developer and UI/UX Javascript specialist.Check out my blog articles, React.JS and Vue.JS UI components at the code laboratory.Feel free to take a look at my latest projects below.Based in London, UK. 
author_email: "john@devlopr.com"
author_location: India
author_website_url: "https://yourwebsite.com"

# social links
twitter_username: yourusername
github_username:  minmon98
facebook_username: PhiVanMinh
linkedin_username: yourusername
behance_username: yourusername
instagram_username: minmon98
medium_username: yourusername 
telegram_username: yourusername
dribbble_username: yourusername 
flickr_username: yourusername